print(abs(1.3))
print(abs(-5))
print(divmod(5, 3))
print(pow(2, 2))
print(pow(2, 4))
print(2 ** 2)
print(2 ** 4)
print(2+1*5)
print('Gongbro'+'Gongbro')
#print('Gongbro' * 'Gongbro')
#print('Gongbro'+1)
print('Gongbro'+str(1))
print(True+True)
print(True+True+True)
print(False+False)
print(True-True)
#print(True/False)
